// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ActionRow': string;
  'ActionRow_Group': string;
}
export const cssExports: CssExports;
export default cssExports;
