// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Spinner': string;
  'Spinner_Path': string;
  'Spinner_Track': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
