// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tab': string;
  'Tab___Active': string;
  'Tab___Disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
