// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Post': string;
  'Post_Body': string;
  'Post_Date': string;
  'Post_Image': string;
  'Post_Image___NoSync': string;
  'Post_SyncStatus': string;
  'Post_Title': string;
}
export const cssExports: CssExports;
export default cssExports;
