// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TableNav': string;
  'TableNav_ActionGroup': string;
  'TableNav_Actions': string;
  'TableNav_Pages': string;
  'TableNav_PaginationLinks': string;
}
export const cssExports: CssExports;
export default cssExports;
