// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'ModalBG': string;
  'Modal_Buttons': string;
  'Modal_Content': string;
  'Modal_Title': string;
}
export const cssExports: CssExports;
export default cssExports;
