// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Badge': string;
  'Badge___Success': string;
  'Badge___Warning': string;
}
export const cssExports: CssExports;
export default cssExports;
